version: '3.7'

services:
  # MySql database service
  mysqldb:
    image: "mysql:8.0"
    restart: always
    container_name: mysql-db
    ports:
    - 3306:3306
    networks:
      - twitter-net
    environment:
      MYSQL_DATABASE: spring-twitter-clone
      MYSQL_USER: yogesh_one
      MYSQL_PASSWORD: Yogesh_pw
      MYSQL_ROOT_PASSWORD: Yogesh_Rpw    
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    

  # MySql Web UI using php my admin
  php-my-admin:
    image: phpmyadmin
    restart: always
    container_name: php-my-admin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - twitter-net

  # Backend spring boot application
  backend:
    build: ./backend
    container_name: api-container
    restart: always
    ports:
      - 8080:8080
    networks:
      - twitter-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/spring-twitter-clone?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2
    

  # Frontend angular application
  frontend:
    build: ./frontend
    container_name: webapp-container
    ports:
      - 4200:4200
    links:
      - backend
    networks:
      - twitter-net
    
networks:
  twitter-net: