version: '3.4'

services:
  backend:
    image: api
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8080:8080
  frontend:
    image: web
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 4200:4200
  db:
    image: mysql
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8080:8080